//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.10 at 02:39:13 PM IST 
//


package com.ooyala.playback.url;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adFirstPlay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adFrequency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adPlayTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
public class AdPlugins {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "adFirstPlay")
    protected String adFirstPlay;
    @XmlAttribute(name = "adFrequency")
    protected String adFrequency;
    @XmlAttribute(name = "adPlayTime")
    protected String adPlayTime;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the adFirstPlay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdFirstPlay() {
        return adFirstPlay;
    }

    /**
     * Sets the value of the adFirstPlay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdFirstPlay(String value) {
        this.adFirstPlay = value;
    }

    /**
     * Gets the value of the adFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdFrequency() {
        return adFrequency;
    }

    /**
     * Sets the value of the adFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdFrequency(String value) {
        this.adFrequency = value;
    }

    /**
     * Gets the value of the adPlayTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdPlayTime() {
        return adPlayTime;
    }

    /**
     * Sets the value of the adPlayTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdPlayTime(String value) {
        this.adPlayTime = value;
    }

}
