//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 02:24:28 PM AEDT 
//


package com.ooyala.playback.url;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ooyala.playback.url package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ooyala.playback.url
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testdata }
     * 
     */
    public Testdata createTestdata() {
        return new Testdata();
    }

    /**
     * Create an instance of {@link Test }
     * 
     */
    public Test createTest() {
        return new Test();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link EmbedCode }
     * 
     */
    public EmbedCode createEmbedCode() {
        return new EmbedCode();
    }

    /**
     * Create an instance of {@link Pcode }
     * 
     */
    public Pcode createPcode() {
        return new Pcode();
    }

    /**
     * Create an instance of {@link Plugins }
     * 
     */
    public Plugins createPlugins() {
        return new Plugins();
    }

    /**
     * Create an instance of {@link AdPlugins }
     * 
     */
    public AdPlugins createAdPlugins() {
        return new AdPlugins();
    }

    /**
     * Create an instance of {@link AdditionalPlugins }
     * 
     */
    public AdditionalPlugins createAdditionalPlugins() {
        return new AdditionalPlugins();
    }

    /**
     * Create an instance of {@link Pbid }
     * 
     */
    public Pbid createPbid() {
        return new Pbid();
    }

    /**
     * Create an instance of {@link BrowsersSupported }
     * 
     */
    public BrowsersSupported createBrowsersSupported() {
        return new BrowsersSupported();
    }

    /**
     * Create an instance of {@link SslEnabled }
     * 
     */
    public SslEnabled createSslEnabled() {
        return new SslEnabled();
    }

}
